server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: devtrack
  
  datasource:
    url: jdbc:postgresql://localhost:5432/devtrack_db
    username: postgres
    password: postgres_secure_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# Custom Application Configurations
app:
  jwt:
    # Secure HSM/environment-friendly 512-bit Base64-encoded secret for HS512 cryptographic signing.
    secret: dGhpc2lzYW5leHRyZW1lbHlzZWN1cmVhbmRsb25nc2VjcmV0a2V5Zm9yZGV2dHJhY2thcHBsaWNhdGlvbnBsdXNleHRyYWNhcmFjdGVyc2ZvcmNvbXBsaWFuY2U=
    expiration-ms: 86400000 # 24 Hours
